don't use sudo in script

diff --git a/install.sh.in b/install.sh.in
--- a/install.sh.in
+++ b/install.sh.in
@@ -1,10 +1,10 @@
 { # Prevent execution if this script was only partially downloaded
 
-set -e
+set -Eeuo pipefail
 
 dest=/nix
 tarball_name=@tarball_name@
-expected_sha256=@expected_sha256@
+tarball_sha256=@tarball_sha256@
 env_store_path=@env_store_path@
 
 log() {
@@ -16,30 +16,45 @@ die() {
     exit 1
 }
 
-if [ -z "$USER" ]; then
-    die "\$USER is not set."
-fi
-
 require_util() {
     type "$1" > /dev/null 2>&1 || command -v "$1" > /dev/null 2>&1 || \
-        die "You do not have '$1' installed, which is necessary to $2."
+        die "This script requires '$1', which could not be found."
 }
 
-require_util sha256sum "verify the integrity of the binary tarball"
-require_util tar "unpack the binary tarball"
-require_util sudo "create $dest"
+check_dest() {
+    if [ -z "$UID" ]; then
+        die "\$UID is not set."
+    fi
+
+    log "Checking for empty '$dest' with uid='$UID' mode='0755'..."
+
+    if [ ! -e "$dest" ]; then
+        log "'$dest' does not exist. Please create it (e.g. with 'sudo install -d -m 0755 -o $UID $dest') and re-run this script."
+        exit 1
+    fi
+
+    dest_mode_and_uid="$(stat -c "%f %u" "$dest")"
+    if [ "$dest_mode_and_uid" != "41ed $UID" ]; then # 040755
+        die "'$dest' is not a directory with uid='$UID' and mode='0755'."
+    fi
+    if [ -n "$(ls "$dest")" ]; then
+        die "'$dest' is not empty."
+    fi
+}
+
+check_dest
+
+require_util wget
+require_util sha256sum
+require_util tar
 
 tarball="$(dirname $0)/$tarball_name"
 
 log "Verifying the integrity of '$tarball'..."
-actual_sha256="$(sha256sum "$tarball" | cut -c 1-64)"
-if [ "$expected_sha256" != "$actual_sha256" ]; then
-    die "SHA-256 hash mismatch in '$tarball': expected $expected_sha256, got $actual_sha256."
+observed_sha256="$(sha256sum "$tarball" | cut -c 1-64)"
+if [ "$tarball_sha256" != "$observed_sha256" ]; then
+    die "SHA-256 hash mismatch in '$tarball': expected $tarball_sha256, got $observed_sha256."
 fi
-
-cmd="mkdir -m 0755 $dest && chown $USER $dest"
-log "Creating '$dest' by running '$cmd' using sudo..."
-sudo sh -c "$cmd"
 
 log "Unpacking '$tarball' into '$dest'..."
 tar -xz -f $tarball -C $dest --strip 1
